### PR TITLE
The Bridges Maps

### PR DESCRIPTION
**Pull request by Ewan884**
Upload of Mineplex Maps for The Bridges

### CODE REVIEW

**Comment by timing1337** [comment]
These don't have WorldConfig.dat which may cause confusion.

Though the main purpose of this repo isnt about archiving but I would accept this if you move it to another folder!

**Review by timing1337 — CHANGES_REQUESTED** [review]
Move to another folder

**Comment by Ewan884** [comment]
Forgot about worldconfig, a seperate map archive folder better?

**Comment by timing1337** [comment]
LGTM!

**Pull request merged**
