### PR TITLE
Making your code compile

### PR DESCRIPTION
**Pull request by Tvhee-Dev**
Thank you for reviewing this pull request!

I have been working on your code for a while today, I have tried fixing all broken dependencies. There was one problem: I do not have the code for the anticheat, so I had to remove these dependencies. Other than that, please make sure to test!

If you have any questions, make sure to ask!

Have a nice day!
Tvhee

### CODE REVIEW

**Comment by nitrog0d** [comment]
💀

**Comment by timing1337** [comment]
I feel like you hardcoded quite a lot of thing (from stripping api calls to Webserver, databases..)

Also alot of the commented out codes were also removed, i would like those to be added again

**Comment by timing1337** [comment]
Also mind telling me how did you compile with maven? Now im getting weird ass issues out of nowhere

**Comment by Tvhee-Dev** [comment]
Hello,

Thanks for your quick reply! I can tell you what I've done:
1. Removing the anti-cheat dependencies from the project / code
2. Moving dependencies from the child pom file to the parent pom file
3. Where needed solving compile errors

I do not exactly which code you ment by "commented", could you clarify that for me?

That the plugin does not compile on your side is weird, maybe you are using other dependency repositories then me

**Comment by timing1337** [comment]
Closed, fixed in later commits

**Pull request closed without merging**
