### PR TITLE
Added Redis help python script, and temp fix to hub load to allow Duels but not Tron

### PR DESCRIPTION
**Pull request by petethepossum**

### CODE REVIEW

**Review by petethepossum — COMMENTED** [review]
Need to add a tutorial or README so people with little python knowledge can run this

**Comment by petethepossum** [comment]
Now Tron is fixed will update the pull request within 24 hours to include redis but not tron comment out

**Comment by timing1337** [comment]
> Now Tron is fixed will update the pull request within 24 hours to include redis but not tron comment out

Oh alright just about to say, i'll look at this when you update, thank you in advance :D

**Comment by petethepossum** [comment]
My comment disappeared but I saw your reply :)

**Pull request closed without merging**
